language: ruby
rvm:
  - 2.1.2
env:
 - TEST_SUITE=minitest
 - TEST_SUITE=rubocop
gemfile:
 - gemfiles/chef-11
 - gemfiles/chef-10
cache: bundler apt
script: bundle exec rake test:$TEST_SUITE
matrix:
  fast_finish: true
  allow_failures:
    - env: TEST_SUITE=rubocop
  include:
    - rvm: 1.9.3
      gemfile: gemfiles/chef-11
      env: TEST_SUITE=minitest
    - rvm: 1.9.3
      gemfile: gemfiles/chef-10
      env: TEST_SUITE=minitest
