language: ruby
rvm:
  - 2.0.0
  - 1.9.3
  - rbx-19mode
  - ruby-head
env:
 - TEST_SUITE=minitest
 - TEST_SUITE=rubocop
gemfile:
 - gemfiles/chef-11.8.2
 - gemfiles/chef-10.30.2
 - gemfiles/chef-master
cache: bundler apt
script: bundle exec rake test:$TEST_SUITE
matrix:
  fast_finish: true
  allow_failures:
    - env: TEST_SUITE=rubocop
    - rvm: ruby-head
    - gemfile: gemfiles/chef-master
